### ISSUE TITLE
An error occurs in the miss.rmiss in the raytracingshadows demo. I'm using visual studio2019

### ISSUE THREAD

**Issue by WdsPjm** [SaschaWillems/SPIRV-VSExtension#10]
![image](https://github.com/SaschaWillems/SPIRV-VSExtension/assets/52599568/0f49bf0d-f610-4aaf-89e0-7442c4bcdf1d)

**Comment by SaschaWillems** [comment]
The ray tracing extension requires a newer SPIR-V environment.

You need to change it in the extensions' setting pane to e.g. spirv1.4:

![image](https://github.com/SaschaWillems/SPIRV-VSExtension/assets/10283127/ebc93fab-bc8c-4937-82f4-724b3154b57e)
