### ISSUE TITLE
Support for VS 2017?

### ISSUE THREAD

**Issue by krupitskas** [SaschaWillems/SPIRV-VSExtension#2]

**Comment by SaschaWillems** [comment]
Works fine with VS2017. There is a separate [branch](https://github.com/SaschaWillems/SPIRV-VSExtension/tree/VS2017) if you want to compile yourself, but I also uploaded a VS2017 compatbile extension to the [VS marketplace](https://marketplace.visualstudio.com/items?itemName=SaschaWillems.SPIRV-VSExtension).

**Comment by Warezovvv** [comment]
Not working for me. I have 2017 Enterprise.

**Comment by Warezovvv** [comment]
Also in your Readme written that only 2015 supported

**Comment by SaschaWillems** [comment]
> Not working for me. I have 2017 Enterprise.
I only tested with the community editions. Looks like the enterprise version has different installation target ID. Will have to check that.

**Comment by Warezovvv** [comment]
Okay, also I using cmake (open folder in vs 2017), not solution. So that's can be problem too, I think, cause even NShader not highlighting anything.

**Comment by SaschaWillems** [comment]
Does the extension install then? If it's installed and you don't see the popup menu entries to compile the shaders they may use a differing extension scheme.

**Comment by Warezovvv** [comment]
Yes, everything others works like a charm except this two. Can you try open your cmake in visual studio 2017 and try compile shader and I will try open your repository with   .sln tonight and write here results

**Comment by SaschaWillems** [comment]
The menu entries only show up if you select a folder or multiple files in the solution explorer with a supported file extension (*.vert, *.frag, *.geom, etc.), so the shader has to be part of the solution file. That works fine over here, but if you create the projects from cmake the shaders won't be added as solution files.

**Comment by Warezovvv** [comment]
Maybe rewrite logic to support any shaders, even not part of solution?

**Comment by Warezovvv** [comment]
I mean that  .sln support folder tree view as and filters. Is that working there?

**Comment by Warezovvv** [comment]
1) Checked in .sln you extension, works like a charm.
2) Updated NShader, it works now in solution and in CMake folder (developer fixed some bugs 25 days ago, so seems like I met some of this bugs).
So I can rename this ticked to - Support for VS 2017 - Open Folder with CMakeLists.txt functionality.

**Comment by SaschaWillems** [comment]
So if I understand this correctly you want the extension to work based on the file-system rather than solution items as the CMakeLists.txt (from my examples e.g.) doesn't add the shaders to the solution? 

If so I'd say the correct way would be to change my CMakeLists.txt to also add the shaders to the solution files for the examples.

**Comment by Warezovvv** [comment]
Mm. Maybe.
I'm not generating .sln based on CMakeLists.txt, as I did this in vs 2015.
Now 2017 generating by itself (you just open folder where cmakelists exists and voila). But I think 2017 making this same way. Need to check out, but maybe it will help.

**Comment by dmiller423** [comment]
`If so I'd say the correct way would be to change my CMakeLists.txt to also add the shaders to the solution files for the examples.`

This isn't exactly how things work these days,  cmake is built into the IDE's and doesn't just generate a sln/vcproj,  the most common scheme doesn't even use msbuild anymore it uses ninja by default.

I think his means of communicating this aren't great,  it would be nice for this to work based on an open file for syntax at least,  though build is probably best handled in cmake.

I realize it's a 2yr old issue, but it's still open so I thought i'd add some input.

**Comment by Keith-Albright-Bose** [comment]
Just tried a compute shader in VS 2017 Enterprise (.comp extension) and no color highlighting, no menu.
Extension is listed as installed.

Added to solution yet no change.  This shader works in VS Code with the Shader languages support for VS Code and Shaderc GLSL Linter extensions.  Was hoping to use this in VS 2017
