### ISSUE TITLE
Support for VS2019?

### ISSUE THREAD

**Issue by emctague** [SaschaWillems/SPIRV-VSExtension#4]
Gotta say, I absolutely love this plugin. Is there any plan to publish on the VS2019 marketplace?

**Update:** Compiling the VS2017 branch from source on VS2019 works fine, after updating dependencies, target version, and a new Prerequisites property in the manifest. However, the resulting VSIX file still won't be installable - I am not sure why yet.

**Update 2:** I have managed to create an installable build for VS2019. [SPIRVExtension.zip](https://github.com/SaschaWillems/SPIRV-VSExtension/files/3094979/SPIRVExtension.zip) It has some tweaks that probably weren't necessary, such as library updates and an advance in version number, that might break behavior I haven't tested - I'm mostly putting it here to show that it's doable, and for anyone else who comes by looking for a copy.

**Comment by SaschaWillems** [comment]
I have published an update to the market place that should add support for VS 2019. I haven't tested with VS 2019 yet, but it's flagged as supported on the marketplace now.

Can you check if this works?

**Comment by emctague** [comment]
I've just tested, it works perfectly in vs2019 without any tweaks.Thank you!
